### ISSUE TITLE
Update Header design

### ISSUE THREAD

**Issue by achrafismyname** [curaOS/source#108]
Update the `Header` component to fit the new [design](https://www.figma.com/file/ZEDDdXRTJxKZH5j5OvGOn4/CURA.RUN?node-id=0%3A1)

- Should be responsive
- Should be relying on variants from `theme.ts` 

> if variants don't exist, make them and mention it in #96

**Comment by devey** [comment]
@achrafismyname you can close this one after you merge #125. But also updated the design so that the flow stays as before where pressing on user name sends you to the bids, so could you create a new one to add the disconnect logo as in the latest designs. This way, we don't have to click on the project name to get to the bids. Sorry for this! 😅

<img width="826" alt="Screenshot 2021-11-22 at 15 44 13" src="https://user-images.githubusercontent.com/5102099/142881331-cfdc8396-5d21-4ce0-a34e-77068aed9633.png">

**Comment by achrafismyname** [comment]
Np! this makes more sense
