### ISSUE TITLE
Error in CI deployment of Storybook for components with hooks

### ISSUE THREAD

**Issue by devey** [curaOS/source#114]
There seems to be something off with `@cura/hooks` within `Storybook`. It might come from the [`Webpack`](https://storybook.js.org/docs/react/configure/webpack) config of `Storybook`. I temporarily ignored the stories with components that use `hooks`.

I could reproduce the error locally after cleaning `/node_modules`, but it seems to work out locally "sometimes", for example, if I tried to build after adding `hooks` with `yalc` and then removed it; that worked.

More details in the [`CI` build]( https://github.com/curaOS/source/runs/4154668472?check_suite_focus=true
).

**Comment by achrafismyname** [comment]
There is some problem with versioning, because when I run `yarn add @cura/hooks`, the package gets updated to `0.0.8` and everything works perfectly fine

`package.json` before 

````JSON
"@cura/hooks": "0.0.6",
````

`package.json` after `yarn add @cura/hooks`
````JSON
"@cura/hooks": "^0.0.8",
````
 https://www.npmjs.com/package/@cura/hooks is `0.0.8` and `packages/hooks/packages.json` is `0.0.6` which is a bit confusing, and i think it's related to the error you are getting.

**Comment by devey** [comment]
I'm not sure that's the problem @achrafismyname. In https://github.com/curaOS/source/pull/111 I tried all types of combination. It seems to only happen with `Storybook` so will merge the PR and keep this one to fix it.

**Comment by devey** [comment]
@achrafismyname This should be easier to fix now, no?

**Comment by achrafismyname** [comment]
I think so, I'll give it a try right now
